version: "3.9"

services:
  db:
    image: postgres:14.2
    container_name: postgresdb
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - blogdb:/var/lib/postgresql/data

  app:
    build: .
    container_name: blogapp
    restart: always
    expose:
      - "8000"
    volumes:
      - ./mysite:/usr/src/app
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: blog_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./mysite/templates:/usr/src/app/templates
      - ./mysite/static:/usr/src/app/static
      - ./mysite/media:/usr/src/app/media
    depends_on:
      - db

volumes:
  blogdb:
