# Generated by Django 4.0.2 on 2022-02-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
