# Generated by Django 4.0.3 on 2022-05-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_blogger_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
